import random
# Random quoter
def Brooklyn():
    brooklyn_99_quotes = [
        'I\'m the human form of the :100: emoji.',
        'Bingpot!', 'Love, it sustains you. It’s like oatmeal',
        'You’re under arrest for ruining something perfect!',
        'Every time you talk, I hear that sound that plays when Pac-Man dies',
        'A place where everybody knows your name is hell. You’re describing hell',
        'I asked them if they wanted to embarrass you, and they instantly said yes',
        'Sarge, with all due respect, I am gonna completely ignore everything you just said',
        'I ate one string bean. It tasted like fish vomit. That was it for me',
        'The English language cannot fully capture the depth and complexity of my thoughts, so I’m incorporating emojis into my speech to better express myself. :wink:',
        'Move over, Peralta! Move over! Okay. And if I may do a third toast, it’ll be focused primarily on the mango yogurt',
        'Fine, but in protest, I’m walking over there extremely slowly!',
        'Actually, someone reported that they couldn’t find your head. But we found it; it was up your butt. You’re a fireman; you should know how to treat that burn',
        'you\'re always bothering me',
        'I just negotiated my baby girls down from a pony to a hamster. Little fools',
        'I wasn\'t hurt that badly. The doctor said all my bleeding was internal. That\'s where the blood\'s supposed to be',
        'No, it\'s probably just an empty, white cube with a USB port in it for him to plug his finger in when he\'s on sleep mode',
        'Jake: I love this. Tux on, guns out- I feel like James Bond, and you are my mysterious femme fatale that I\'ve been partnered with: Maxi...Pads.\nAmy: Maxi Pads?\nJake Peralta: I don\'t know! I didn\'t want to make the name too sexual and I panicked!',
        'Gina: Uh, Jake, wait. What are you doing? Give me the ring.\nJake: Ha! You sound like Gollum.\nGina: That means nothing to me. I don\'t see those movies, I\'m too pretty.',
        'Terry: You don\'t care who you piss off, do you?\nGina: Not in the slightest',
        'Well done, detectives. That is if you were trying to disappoint me',
        'Gina Linetti: I fixed this!\nCharles: It\'s working! How\'d you do that?\nGina: I grew up with a smoke machine in the apartment, Charles. I like to enter the kitchen in the morning with vivacity.',
        'Jake: Be myself? Charles, I have one day to win over Amy\'s dad. How long did it take before you guys started liking me?',
        'Rosa: Couple weeks.\nSergeant Jeffords: Six months.\nCaptain Holt: Jury\'s still out',
        'Jake: See, Charles? \"Be myself,\" what kind of garbage advice is that? I hope you\'re not telling Nikolaj that crap\nCharles: [correcting] Nikolaj\nJake: Ugh.',
        'I’m not going to stand here and listen to you accusing me of things I clearly did.',
        'Jake: I\'m so happy I want to shout it from the rooftops!\nAmy: And he has. We\'ve gotten several noise complaints',
        (
            'Cool. Cool cool cool cool cool cool cool,'
            'no doubt no doubt no doubt no doubt'
        )
    ]

    return random.choice(brooklyn_99_quotes)

def AlwaysSunnyQuote():
    SunnyQuotes = ["So you think not eating cat food is putting on airs?"," We’re trying to give you the Christmas spirit, dickhole!",
                   "Yippie-kay-yay, Mr. Falcon!",
                   "Charlie, make a move. Just tell her you wanna bang her.",
                   "Mac, you have an exceptional number of bugs in your teeth. You’re gonna wanna rinse those out. It’s disgusting.",
                   "Grain alcohol, baby! Whenever there’s a potential riot, I’m getting blasted on grain alcohol.",
                   "Okay, Mr. Mayor. Feast your ears on that Spin Doctors mix.",
                   "Dude, do you have a boner right now?",
                   "Name’s Artemis. I have a bleached asshole",
                   "And you know what happens with Tokyo drifting? It leads to bickering. Which, of course, leads to karate.",
                   "The acid’s makin’ me feel like I gotta take a dump.",
                   "Dude, I swear to God, if you try and give me a noogie, I will yank your underwear over your head so hard your asshole will rip in half.",
                   "[Holding a calculator] What are you?",
                   "Any amount of cheese before a date is too much cheese.",
                   " [Reading a note from Charlie] Taked baby. Meet at later bar, night or day sometime.",
                   "Smoke some cigarettes. The smoke will suffocate the bacteria in your stomach.",
                   "Yeah, well, you’ve never once seen me wash my testicles either, but that doesn’t mean I don’t do it every Friday.",
                   "Animals should be food, rugs and trophies. Why do you think I’m wearing a leather suit?",
                   "Goddammit, Jack Bauer. You really are the man.",
                   "Dennis, you don’t wanna go anywhere near a court. How many bench warrants for sexual misconduct do you have? Yeah, and Frank, how many unregistered guns are in your car right now?",
                   "Oh, look at me! The millionaire who goes to see doctors!",
                   "I’m just saying, based on that story that you just told me, I’m fairly certain that those Santas were running a train on your mom for money.",
                   "Then start breakin’ bricks, wet nips!",
                   "That’s Tammy, Trey’s ex-girlfriend. This is classic Tammy. Trey broke up with Tammy because Maureen Kinallen said that she saw Tammy flirting with Walt Timby at a party. But she was only doing it to make Trey jealous because, you know, she thought that Trey secretly liked Erin Hannabry. But Trey didn’t like Erin Hannabry. It was all a bunch of bull.",
                   "RUM HAM! RUM HAM! I’m sorry rum ham! I’m sorry…",
                   "Mac, I’m gonna stop you right there. First of all, your breath smells like an old lady fart passing through an onion. Secondly, I know you’re trying to manipulate me, and it’s not going to work. Get your hand off my shoulder, because I’ve got a fatty to burn.",
                   "You’re a stone cold fox, Margaret. You’re a stone cold fox, and I want you. I gotta have you. I need you. I want you inside me. But you know that, don’t you, Margaret?",
                   "Oh, I get it. Cute. You leave this pen here and people are supposed to think, \“Wait, that looks like a dick.\”",
                   "Well, I don’t know how many years on this Earth I got left. I’m gonna get real weird with it.",
                   "Take a look at Rex here. That is a body that just won’t quit. And I bet if you pop those pants off, you’re gonna find a bird that just won’t quit, either. And I think that’ll come in handy in this situation. I think the problem here is that your body quit. Your bird quit. And, unfortunately, it’s no longer legit.",
                   "Here’s a confession: I’m in love with a man. What? I’m in love with a man. A man called God. Does that make me gay? Am I gay for God? You betcha!",
                   "Hi. Um, I’m a recovering crackhead. This is my retarded sister that I take care of. I’d like some welfare, please.",
                   "I’m not asking you to do much. Just turn a blind eye while I rob this place stupid.",
                   "How’s that ass feel? [slaps Dennis in the ass]",
                   "Isn’t that amazing? You ask to see a woman’s breasts on the street, you get slapped. You give her a free t-shirt and videotape it, and the clothes come right off.",
                   "[In Boston accent] Ohhh, bet you read a lotta Gordon Wood, huh? You read your Gordon Wood and you regurgitate it from a textbook and you think you’re wicked awesome doin’ that, and how ’bout ‘dem apples? And all that Gordon Wood business.",
                   "You know what, Dee? I don’t wanna hear about your dreams, okay? I hate listening to people’s dreams. It’s like flipping through a stack of old photographs. If I’m not in any of ’em and nobody’s having sex, I just- I don’t care.",
                   "I mean, does my scar look like a dog’s vagina? You know, maybe. I don’t know. I’m not gonna sit here and try and get inside the mind of a dog. I mean, that’s God’s work. Well, not that I believe in God. I don’t. Not since that Chinaman stole my kidney",
                   "Then, I’ll just regress, because I feel I made myself perfectly redundant.",
                   "[Reading Charlie’s script] \“Hello fellow American. This you should vote me. I leave power. Good. Thank you. Thank you. If you vote me, I’m hot.\”What?\“ Taxes. They’ll be lower. Son. The democratic vote for me is right thing to do, Philadelphia. So do.\”",
                   "Do not plug an open wound with trash.",
                   "It’s fetish-fetish shit! I like to bind. I like to BE bound!",
                   "I’m gonna pinch their dicks with this lobster.",
                   "This bar runs on trash, dude. This bar is totally green that way.",
                   "Well, maybe you’re a whore, you stupid, ugly, homeless bitch!",
                   "Okay, well, “Charlie work” is like, you know, like basement stuff, cleaning urinals, uh, blood stuff, your basic slimes, your sludges, anything dead or decaying. You know, I’m on it. I’m dealing with it.",
                   "Bruce is not banging any baby dudes!",
                   "Oh, get a job? Just get a job? Why don’t I strap on my job helmet and squeeze down into a job cannon and fire off into job land, where jobs grow on jobbies?!",
                   "Wanna go get sweaty in the bathroom?",
                   "[Singing] I got the Lord. I got the Lord. I got the good Lord, he’s goin’ down on me.",
                   "They’re actors. They’re trying to create an illusion. In the “Lord of the Rings” movie, Ian McKellen plays a wizard. You think he goes home at night and shoots laser beams into his boyfriend’s asshole? I don’t think so, dude. Tom Cruise is a midget, alright, but he plays guys that are normal size in movies.",
                   "What is this word, spa? I feel like you’re starting to a say a word and you’re not finishing it. Are you trying to say spaghetti? Are you taking me for a spaghetti day?",
                   "I’m not fat. I’m cultivating mass.",
                   "Your mom doesn\’t know dick! She\’s a dumb, fat cow. And your sister, she\’s a stupid little shit-mouthed bitch, isn\’t she?",
                   "[Speaking like a radio host] TWO wars?! We’re in the midst of two wars all at once–Now the United States of America is engaged in both of these wars?",
                   "Roxy, God bless you. You were a good whore. You serviced me like no other whore ever did. Not only my crank, but my heart. And…I\’m gonna miss ya. Amen.",
                   "You should have seen how passionate he got when I showed him the dick flyer.",
                   "It involves pulling up our bootstraps, oiling up a couple of asses and doing a little plowing of our own. Pow!…Not gay sex.",
                   "Cat in the wall, eh?! Okay, now you’re talking my language.",
                   "I don\’t appreciate being paraphrased. Now, I choose my words very deliberately.",
                   "We\’re gonna get all in your face and point out your faults.",
                   "[Vietnamese music playing] This music sounds like whales raping each other.",
                   "Well, that\’s gonna be a problem; I laser. It\’s like a turtle\’s shell down there.",
                   "Oh, shit. Look at that door, dude. See that door right there? The one marked \“pirate?\” You think a pirate lives in there?",
                   "Fight Milk! The first alcoholic dairy based protein drink for bodyguards!",
                   "Later, boners.",
                   "I\’m a…full-on rapist, you know? Uh, Africans, dyslexics, children, that sort of thing.",
                   "Bite my bird.",
                   "Who am I supposed to vote for? Am I supposed to vote for the Democrat who\’s gonna blast me in the ass or the Republican who\’s blasting my ass?",
                   "Paddy\’s shotgun, bro. You get blasted in the mouth!",
                   "I eat stickers all the time, dude!",
                   "I\’m not gonna be buried in a grave. When I\’m dead, just throw me in the trash.",
                   "Later, dudes. S you in your A\’s, don’t wear a C and J all over your B\’s.",
                   "I hear the guy hangs dong and I\’m very interested in seeing that.",
                   "THIS ISN\’T OVER UNTIL I SAY IT\’S OVER!",
                   "If you\’re in my room, you\’re always being filmed.",
                   "See, I’ve always got an A, B and C strike plan to get us out of any potentially life-threatening situation.",
                    "\‘Cause if the girl said \“no,\” then the answer obviously is \“no.\” But the thing is, is she\’s not gonna say \“no.\” She would never say \“no,\” because of the implication.",
                   "Oh, you\’re definitely gonna end up doing gay porn with this tiny little body of yours.",
                   "I got my Magnum condoms; I got my wad of hundreds. I\’m ready to plow.",
                   "Can I stop you, though? You keep using this word \“jabroni.\” And…it\’s awesome!",
                   "Everybody\’s dying, bitch.",
                   "Okay, listen. Listen, you remember that night at Dooley\’s pool party? On that fine summer eve, when I did that double jackknife twist and blew everybody\’s tits off. You remember that? And then I went down on Chrissy Orlando on the trampoline later that night?",
                   "[Singing] I\’m gonna rise up. I\’m gonna kick a little ass. Gonna kick some ass in the U.S.A. Gonna climb a mountain. Gonna sew a flag. Gonna fly on an eagle. I\’m gonna kick some butt. I\’m gonna, drive a big truck. I\’m gonna rule this world. I\’m gonna kick some ass. I\’m gonna rise up. I\’m gonna kick a little ass. ROCK, FLAG AND EAGLE!",
                   "Flush that turd down the drain!",
                   "I browned out that evening.",
                   "See you later, Dirt Grub and Ronnie the Rat. Hope you suck each other\’s rotten peckers until you get mouth cancer.",
                   "Boys are out tonight, huh?",
                   "I will SMASH your face into a- into a jelly!",
                   "So come on, you ol\’ son of a gun, and let Buster do a line off your boner.",
                   "Oh, you unzipped me! It\’s all coming back! It\’s all coming back; I hate you! It’s all coming back, you understand?! I DON’T LIKE IT! I DON’T LIKE TO THINK ABOUT IT!",
                   "[Singing] Dayman, fighter of the Nightman, champion of the sun, you\’re a master of karate and friendship for everyone. Dayman!",
                   "I will eat your babies, bitch!",
                   "I shoulda popped my shirt off. Goddammit, really shoulda popped that shirt off",
                   "Wildcard, bitches! Yee-haw!",
                   "Yeah, we both got punked, Frank. We both got punked. These kids these days, I\’ll tell you what, they\’re nothing like we used to be back when we were in fraternities. They have no respect for anybody. Okay? They\’re like-they\’re like stupid little goddamn savages. I mean, I came in there, right, and I was polite and I was nice to them. I was cordial. And they completely goddamn disrespected me, little IDIOTS! IDIOTS! I was completely respectful. They\’re supposed to be my brothers, right? They’re my brothers? Nooo, no. That\’s not fun. What they were doing wasn\’t fun. They kept zapping us, and zapping us! IDIOTS! SAVAGES! IDIOTS! IDIOTS!",
                   "Dennis, if I was looking for safe, I wouldn\’t be sticking my dick through a wall.",
                   "Is your cat making TOO MUCH NOISE ALL THE TIME?",
                   "Hey-o! What’s up, bitches!"
                   ]
    return random.choice(SunnyQuotes)


def RandQuote():
    return 'I\'m sO rAnDoM :rofl: :stuck_out_tongue_closed_eyes: :zany_face:'